### ISSUE TITLE
Ubi sunt links to Commons pages!

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Commons#19]
1. Items sent to Commons status and details are Ok and Ok, with no link to page in Commons (may not have been sent to Commons, see next section).
   
   Huh, I’ve introduced a bug! I’ll add that back in (I think it was there before?)

before?) —yes, it was in there before. And I did see that my items were sent, but they weren’t in my display case.

https://chnm.basecamphq.com/W4805250

**Comment by zerocrates** [comment]
No Latin in issue titles, please.
