### ISSUE TITLE
As a contributor to Commons, I want to see a list of items pushed to the commons and their status

### ISSUE THREAD

**Issue by patrickmj** [omeka/plugin-Commons#21]
@sheilabrennan @sharonmleon This is something that I think we'd talked about long ago, and is built in a rudimentary (and buggy) way. Could I ask for some more details about what this should look like, and what actions, if any, a site admin should be able to take on that screen? Thanks!

ccing @kimisgold to ask if she has any thoughts on this page, too.

**Comment by sheilabrennan** [comment]
In the admin Commons plugin page?
Is this the appropriate place to remove something from the Commons, or will this action occur individual admin/item or collection/show pages?

As a site admin, I want to browse and sort a list of items and collections pushed to the Commons.
... I want to change the status of a collection or of an item (if this can't be done elsewhere in Omeka).

**Comment by patrickmj** [comment]
I'm thinking of one of the pages in the Commons plugin. So far, I imagining that actions would be available on item and collection edit pages. Not sure if actions (like remove from Commons) makes sense here. It would certainly make the interface more cluttered, and I'm not sure what would be gained.

What sorting and/or filtering need to be there? That is, sort by what fields, and filter by what fields?

**Comment by sheilabrennan** [comment]
Ideally, the Commons status be visible in the admin/items/browse, and then also added to the Quick Filter. Then, we don't need to list all of the items and collections on a separate page in the plugin's interface.

Could that work?

**Comment by patrickmj** [comment]
there's not a way to add it to the quick filter, but it could be added to the items search.

the status could be visible in the browse, but only in the details section, which is hidden by default. Is that still okay?

Update. My bad, it wouldn't have to be buried in the details.

**Comment by sheilabrennan** [comment]
I think that could work.

**Comment by kimisgold** [comment]
I'd actually prefer it to be in the details, if that's okay. Otherwise, it'd be an extra line on each item to lengthen the page, and I don't think it's information the Commons contributor needs every time he/she visits the items/browse view.

**Comment by sheilabrennan** [comment]
Sure, that is fine.
