### ISSUE TITLE
Various actions need confirmation flash messages

### ISSUE THREAD

**Issue by kimisgold** [omeka/plugin-Commons#22]
Each of these actions made as a Commons contributor need some kind of error or success flash message.
- [x] Whenever a change is made to a field on the 'Site Information' view.
- [x] Whenever on the 'Share' view, the contributor checks "export all the items" and updates the commons.
- [x] Whenever changes to 'Settings' are saved.

**Comment by patrickmj** [comment]
At least for the 2.x version, these should be in place
