### ISSUE TITLE
Item images do not get pushed to Omeka Commons

### ISSUE THREAD

**Issue by kimisgold** [omeka/plugin-Commons#25]
As a Commons contributor, I attached image files to my items, and shared those items with the Commons. The items were successfully shared with the Commons, but there is no record of the attached files in the Commons admin records of the items.

**Comment by patrickmj** [comment]
I've had some problems with my local Omeka Commons site complaining about file mime types in the past. Could you try turning off the check for allowed mime types and see if that makes progress?
