### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by sheilabrennan** [omeka/plugin-Commons#27]
@patrickmj 

Notice: Use of undefined constant HELPERS - assumed 'HELPERS' in /websites/omekadev/home/www/sbrennan/SearchTestO2/SearchTestO2/plugins/Commons/plugin.php on line 7 Warning: require_once(HELPERS): failed to open stream: No such file or directory in /websites/omekadev/home/www/sbrennan/SearchTestO2/SearchTestO2/plugins/Commons/plugin.php on line 7 Fatal error: require_once(): Failed opening required 'HELPERS' (include_path='/websites/omekadev/home/www/sbrennan/SearchTestO2/SearchTestO2/application/libraries:/websites/omekadev/home/www/sbrennan/SearchTestO2/SearchTestO2/application/models:.:/usr/share/pear:/usr/share/php:/websites/omekadev/home/www/sbrennan/SearchTestO2/SearchTestO2/plugins/DublinCoreExtended/models:/websites/omekadev/home/www/sbrennan/SearchTestO2/SearchTestO2/plugins/OaipmhHarvester/models:/websites/omekadev/home/www/sbrennan/SearchTestO2/SearchTestO2/plugins/SimpleVocab/models:/websites/omekadev/home/www/sbrennan/SearchTestO2/SearchTestO2/plugins/SimpleVocab/libraries:/websites/omekadev/home/www/sbrennan/SearchTestO2/SearchTestO2/plugins/SimplePages/models:/websites/omekadev/home/www/sbrennan/SearchTestO2/SearchTestO2/plugins/ExhibitBuilder/models:/websites/omekadev/home/www/sbrennan/SearchTestO2/SearchTestO2/plugins/LcSuggest/models:/websites/omekadev/home/www/sbrennan/SearchTestO2/SearchTestO2/plugins/LcSuggest/libraries:/websites/omekadev/home in /websites/omekadev/home/www/sbrennan/SearchTestO2/SearchTestO2/plugins/Commons/plugin.php on line 7

**Comment by zerocrates** [comment]
Using the master or omeka-1.x branch instead of omeka-2.x?

**Comment by sheilabrennan** [comment]
Master – was not advised to grab anything else.

**Comment by zerocrates** [comment]
I don't know anything about what's going on here, but master looks very old.

omeka-2.x looks like the branch to work with for a 2.0 installation.

**Comment by sheilabrennan** [comment]
Will give it a try.

**Comment by patrickmj** [comment]
Yes, omeka-2.x branch is the one to use. The story that fits the situation most closely is probably <a href="https://omeka3.atlassian.net/browse/OMEKA-256">256</a> -- part of the move to using Jira to manage the work.
